### ISSUE TITLE
Output given in the Problem 2 of Master branch is not correct

### ISSUE THREAD

**Issue by Prasad108** [TechForumIndia/CodeMaster-v1.0#1]
Hi @abhijit-g  , @arunkaneria ,

I have gone through the output given in the problem 2 of Master branch. Is it correct output.txt given to us for  cross verification?
If Yes have some doubt about it 
It is simple Logic that ,
### **For 1 switch for all Even number of claps Bulb will be OFF** 

Input from Input2.txt and corresponding outputs 

Input Line   No | N(Number of Switches) | C (Number OfClapps) | Output Line No | Output Given in File | Expected
-- | -- | -- | -- | -- | --
44 | 1 | 4197832 | 43 | ON | OFF
98 | 1 | 7659036 | 97 | ON | OFF
228 | 1 | 12788738 | 227 | ON | OFF
268 | 1 | 6 | 267 | ON | OFF
358 | 1 | 643978 | 357 | ON | OFF

**Comment by abhijit-g** [comment]
Hello Prasad,
It is pushed by one of our participant and not an actual solution. I will update master with Solution and correct output for both problem soon ;)
